### ISSUE TITLE
integration with KAddressbook version 16.04

### ISSUE THREAD

**Issue by gntech** [dragotin/kraft#1]
I cant seem to get any connection between Kraft and KAddressbook 16.04

When I do the setup wizard and is about to choose my own address all the fields are blank. Even tough my address book exists in KAddressbook and in Kontact.

Is this a known problem with the kde apps 16.04 or Arch Linux?

**Comment by dragotin** [comment]
THe problem is probably that your desktop runs the KF5 addressbook, while Kraft is still on KDE4. The underlying Akonadi is not compatible.

To solve that with a work around, you would need to downgrade Akonadi and KAddressbook to the KDE4 versions. The real solution is a Kraft port to KF5 which is on the way ( https://github.com/dragotin/kraft/tree/kf5 ) but still a long way to go.

**Comment by aseques** [comment]
I can confirm that with recent versions of kraft (0.81) present on ubuntu 18.10 the integration with KAddressbook it's working fine.
