### ISSUE TITLE
invent.kde.org mirroring

### ISSUE THREAD

**Issue by arkadesOrg** [dragotin/kraft#114]
Does it make sense to mirror the project on invent.kde.org?

**Comment by dragotin** [comment]
It probably would. Do you know any policies? Which repository would you suggest?

**Comment by dragotin** [comment]
Well, tbh, KDE requires quite some things to consider and to fulfill. Since I have only a little time that I am able to put on Kraft, I rather prefer to put it on Kraft directly rather than fulfilling all these requirements. To keep up with the high standards of KDE, there is more needed. 

And btw, Kraft started as a KDE project (I was involved in KDE for quite some time and still love the project) but at some point it became clear that Kraft should rather move out there. 

I would have considered to just mirror the project to another git, but keep development on Github. But that does still not seem to be an option.
