### ISSUE TITLE
Missing icons in AppImage

### ISSUE THREAD

**Issue by stefanbaur** [dragotin/kraft#149]
![image](https://user-images.githubusercontent.com/6331105/177143422-2f0859c8-8afe-49ee-999b-29685f7d7741.png)

Hi Klaas,

Comparing the two regions in the screenshot above, the green region has icons, while the red one does not. This happens when using the Appimage "kraft-master-0.98+git13+g006b8bf-lp152.50.1.Build3.2.glibc2.17-x86_64.AppImage", but also with older versions.

I haven't tried out non-AppImage versions yet.

Is this intentional?

Kind Regards,
Stefan

**Comment by noseshimself** [comment]
I have the same problem with the AppImage AND the Debian package. The only way for me to get the icons showing on Debian is compiling the package myself and I have yet to find out why I suddenly succeeded....

**Comment by Ionic** [comment]
Stefan's original issue was caused by him using a Trinity (i.e., KDE 3) icon theme, which doesn't support/supply icons such as `edit-copy`, `folder-documents` etc.

Newer Plasma (KDE 5, maybe even 4) themes do, though, so it's actually a theming issue.

This said, `QIcon::fromTheme` can be supplied with a fallback icon in case the icon theme does not provide the icon it has been queried for, and the fallback icon can be baked into the binary (as a `QResource`). I'd advise shipping and providing fallback icons for things that might not be available in themes.

**Comment by dragotin** [comment]
Same problem here:
![grafik](https://user-images.githubusercontent.com/1070214/180608624-b5624025-bb50-4c49-be76-e267cfefa247.png)

**Comment by noseshimself** [comment]
I don't have the slightest idea where the icons are coming from on my system. A "naked" ChromeOS Debian container doesn't have much pre-installed GUI lebraries at all -- you would be surprised about the stuff being brought in by ``apt install xterm``.

**Comment by dragotin** [comment]
Obsoleted by #175
