### ISSUE TITLE
Support for XRechnung v3.0.1

### ISSUE THREAD

**Issue by Footur** [dragotin/kraft#221]
A new XRechnung standard will be in force soon. It would be great if Kraft supported XRechnung v3.0.1.

- https://xeinkauf.de/app/uploads/2023/09/301-XRechnung-2023-09-22.pdf
- https://xeinkauf.de/xrechnung/versionen-und-bundles/

**Comment by dragotin** [comment]
I added a XRechnung template for version 3.0.1 here: https://github.com/dragotin/kraft/blob/master/reports/xrechnung_301.xrtmpl 

Could you test if that works for you by downloading, adding your specific values like before, and setting it in the Kraft settings dialog, and let me know if it solves your usecase? 

Btw - I realised that there is a bug in the latest stable version of Kraft that the XRechnung generator does not overwrite an already existing xml file. That bug is fixed in master and will be in the next version, but is good to know. That was stealing some time for me...

**Comment by dragotin** [comment]
Seems to be sufficient.
