### ISSUE TITLE
Please reconsider: Document deletion really is necessary!  

### ISSUE THREAD

**Issue by piedrok** [dragotin/kraft#225]
Hi! 

I understand that the deletion of official invoices is not allowed. 

Still it should be possible to delete renegotiated offers, test cases and invoices that have to be rearranged (e.g. a customer wants three different invoices instead of a big cumulative one!) - there are many cases that benefit from deletion... 

In my case I still have a database going ten years back with lots of faulty documents and test cases due to issues with document styling, kraft software updates, database migration problems and lots of testing going along with it. 

Also I do not think any software should hand-hold users - just give a warning that one might run into legal issues by deleting stuff - that's more than enough! Users should have the freedom to create, change and delete invoices on their own volition. 

This is especially important as the styling of documents isn't trivial at all and might need a testing and experimentation. Speaking of me: I needed lot's of fiddling and different versions to get a satisfactory look... 

One first quick and dirty workaround could be a toggle to hide unwanted documents from the documents list (a way to toggle "officially" sent documents immutable would also help to distinguish between faulty and "real" entries"). 

For the moment - is there a tutorial which database entries to delete manually to remove some documents from the database?  

Any improvement in this area would be very much appreciated! 

Thanks a lot for reading, 
pk 

p.s.: Keeping faulty documents around also breaks the obligatory continuous numbering of official invoices (mine are a mess!) - that's technically also illegitimate, isn't it?

**Comment by dragotin** [comment]
Ok. Let's reconsider. I get your points, especially about software that tries to dictate user behavior, that is absolutely not my goal with Kraft obviously.

With Kraft v2 (which is progressing in a branch https://github.com/dragotin/kraft/tree/newshared) there will be a different document livecycle: Documents will be in a draft status until the user finalizes the document, which means sends it to the receiver/customer. In the draft state, deleting is always possible, because the documents do not yet have an official document number out of a number cycle. That will probably solve lots of your concerns.

As soon as a document number was assigned deleting is not remains to be difficult. Maybe a kind of "audit list" where it is exactly documented why the doc was deleted would help.

I would appreciate input from people who are deeper into GoBD - please advise!

**Comment by dragotin** [comment]
a few more details on doc live cycle here: https://github.com/dragotin/kraft/discussions/197#discussioncomment-8791330

**Comment by piedrok** [comment]
First of all: Thanks for your detailed response! 

The changes you are planning sound perfect to me... - one of my issues is (and I assume this might be common) that I start writing an invoice but cannot finish it right away... (e.g. a final call with a customer is still pending)... 

But with your draft concept this issue would be solved once and for all! 

Also I do agree that correct numbering and the keeping of any official (sent) documents should be strongly encouraged... 

Regarding an audit list or a protocol of changes or deletions regarding finished documents is probably a lot of additional work for you - but the solution is perfect. 

Being forced to leave a little note to comment on any changes to finished documents is without question the best practice in any case. 

I still think an additional toggle to hide or archive some documents - just to make them disappear from the list of documents to work with on a regular basis - would be useful to keep things uncluttered and long lists more manageable.  

But whatever you decide I am very glad to hear that there is already progress on a solution which is better than the one I hoped for... - thank you once more! 

Regarding the GoDB: Is there anyone who fully understands and complies with it? 
I do have my doubts... and I am very sure that it's not me... :-( 

Cheers!

**Comment by dragotin** [comment]
Seems like this is fine. Closing.
