### ISSUE TITLE
Bug: Items not editable if copied from previous document

### ISSUE THREAD

**Issue by knalltuete86** [dragotin/kraft#242]
When I create a follow-up document (procedure e.g.: an offer followed by an invoice) and select the Checkbox "copy items from previous document" I'm not able to edit them anymore. The menue items are grayed out.

I usually have items which are offered on demand - so they're charged only if customer need them.
It is a really good workflow to take over the items from the offer to the invoice and only change the type (normal/on demand/alternative) and their amount.

But due to this situation I have to deselect the checkbox every time I have those on-demand-items and select all items again from catalogue.

I guess it's a bug as the Documentation says

> We have now a copy from the offer as an Acceptance of order (**do not forget to adapt Alternative Delivery items and on demand items.**)

I'm using the latest Release v.1.2.1

Thank you!

**Comment by dragotin** [comment]
Yes, I can confirm. That is not intended, aka a bug. I will look into a fix, thanks for reporting.

**Comment by dragotin** [comment]
The reason for this issue is that the ability of the item kind menu depends on the doctype of the document. Some doc types, such as _Rechnung_ for example, can not have demand- or alternative-types. When copying a document to a new doc with a different doc type, the doc type has to be set to _Normal_ if the new doc type does not allow other types.

Interesting bug :-)
