### ISSUE TITLE
Arch - I18N_ARGUMENT_MISSING and Addressbook Integration down

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#37]
Hi

I'm sorry to bothering you. I sent you an email as well. Sometimes it's landing in a Spam Folder. That's the reason I'm posting here as well.

I'm using Arch - KDE. And I have two annoying Problems.
I can't use my Contacts from KAddressBook. 
```
Kraft Addressbook Integration down.
The address book backend is not up and running.
Please check your addressbook integration setup. 
```

Another Problem is
```
 2(I18N_ARGUMENT_MISSING) templates in 2(I18N_ARGUMENT_MISSING) chapters
 last modified at Tuesday, July 10, 2018 2:45:26 AM NZST(I18N_ARGUMENT_MISSING)
```

I tried already a few things but I can't figure it out ... You're might be able to help me or someone else.

Thank you,
Dan

**Comment by dragotin** [comment]
While I think the Akonadi issue is specific to your installation, I found the reason for the second issue you mention here with the i18n framework.

The reason is that I used the KDE i18n() function in a wrong way, confused with the Qt equivalent tr() which I used a lot in another project.

Fix will come.

**Comment by DanSman** [comment]
Hey

I have still the problem with I18N.
Not so much anymore but it's still there.

Mostly in the Catalogs if I change something. And the Documents.
