### ISSUE TITLE
Sending document via email is not supported with kde/kmail

### ISSUE THREAD

**Issue by alxhoe** [dragotin/kraft#47]
When sending a document via email and using kmail on kde, kraft ignores the klick. With thunderbird as standard mailer, sending document is possible.

**Comment by dragotin** [comment]
Kraft should use `xdg-email`

**Comment by dragotin** [comment]
To make Kraft use the xdg-email tool, just add to `$HOME/.config/kraftrc` into the `[system]` section:

```
[system]
mailUA=xdg
```
Otherwise, Kraft continues to try to start thunderbird directly, to stay with the behavior so far. Unfortunately, thunderbird does not work through xdg-email (does not attach the document), that makes this neccessary.
