### ISSUE TITLE
Check WeasyPrint as Replacement for ReportLab

### ISSUE THREAD

**Issue by dragotin** [dragotin/kraft#62]
Would [WeasyPrint](https://weasyprint.org/) a good replacement for the current ReportLab based  PDF generation that is currently in Kraft?

Apart from the fact that ReportLab did a very good job in the past (good quality output docs), it has some downsides that are hard to overcome:

- Difficult language that needs to be used to customize the layout of the PDF output
- Next to no maintenance (AFAIK)
- Some missing features like page sums (a "trending" sum on top and end of each page) and very hard space management between for examples entry texts and the items.

Some good arguments about Weasyprint:

- it renders html to PDF, people probably can customize that easier
- seems to be a vital project
- standalone cli supported, no JavaScript KungFu required as for other alternatives

Some doubts/questions about Weasyprint:

- it has a rather big dependency list, all Python3 stuff
- Can it handle page breaks well, incl. free space management etc.
- Does it have enough features to replace ReportLab?

**Comment by DanSman** [comment]
It seems really good. 

We can try it if it's easy to implement to kraft. 

I will help you wherever I can.

**Comment by andywuest** [comment]
Please do not drop the old PDF rendering. I am still very happy with it (works without problems). It would be better to support both PDF backends - so the users can decide which one they want to use.

**Comment by dragotin** [comment]
Yes, that was what I thought of, having multiple backends for rendering.

@andywuest: Do you render one-page or multiple page documents usually?

**Comment by andywuest** [comment]
> @andywuest: Do you render one-page or multiple page documents usually?
Almost all of the time i have one-pagers. Multi-page documents are the exception.

**Comment by dragotin** [comment]
@liZe do you have input for us?

**Comment by liZe** [comment]
Hello!

> * it renders html to PDF, people probably can customize that easier

It’s true. Even if mastering CSS for print is a long journey, you’ll easily find some webdesigners who can generate pretty HTML+CSS invoices.

> * seems to be a vital project

Indeed.

> * standalone cli supported, no JavaScript KungFu required as for other alternatives

It’s true (note that WeasyPrint doesn’t support JavaScript at all). If you need specific behavior, you can also create a simple custom Python script.

> * it has a rather big dependency list, all Python3 stuff

If you only target Linux desktops, [WeasyPrint is already packaged for many distributions](https://weasyprint.readthedocs.io/en/latest/install.html#linux) (Ubuntu, Debian, Fedora, Arch…), so it shouldn’t be a problem.

If you target Windows or macOS, it’s much harder. WeasyPrint relies on Python dependencies (that are generally easy to install), but also on many packages such as Cairo, Pango and FreeType that must be installed on the system.

> * Can it handle page breaks well, incl. free space management etc.

CSS gives a lot of features related to page breaks, even if they’re not well known (because they’re almost useless for browsers). If you have some invoice samples with explicit requirements, I can try to create a simple template showing what’s possible (and what’s not).

> * Does it have enough features to replace ReportLab?

That’s a good question.

The main difference is that page breaks are automatically handled. That’s a very good point, especially for tables because it’s pretty hard to generate manually. Manual space management is also hard as hell, you can remove the logic from your software and let WeasyPrint handle this. But that’s also a source of trouble, because you’re not able to do what you want during page breaks (including adding "a trending sum on top and end of each page").

Please let me know if I can help you!

**Comment by dragotin** [comment]
@liZe I played a bit with weasyprint and it looks very promising.

One question: Can weasyprint also convert XML files? I tried it with one of the XML files Kraft already produces, and weasyprint does not give an error and produces and PDF, but does not apply any styles. Anything I need to consider, or is that just not implemented? Thanks!

**Comment by liZe** [comment]
> One question: Can weasyprint also convert XML files? I tried it with one of the XML files Kraft already produces, and weasyprint does not give an error and produces and PDF, but does not apply any styles. Anything I need to consider, or is that just not implemented? Thanks!

If by XML files you mean non-XHTML files, then it doesn’t handle them. The library parsing HTML is able to somehow build an HTML tree out of this file (HTML parsers are really forgiving), but WeasyPrint won’t find stylesheets and/or apply styles. Are browsers able to handle these files correctly?

The easiest way to render non-HTML documents with WeasyPrint is to change them into HTML using a custom converter script/function (you can even try XSLT :wink:). By design, WeasyPrint will probably never be able to handle anything but HTML documents.

**Comment by dragotin** [comment]
I added some test and stuff to play around with in directory https://github.com/dragotin/kraft/tree/master/reports/weasyprint

@liZe would you mind to 'review' what I did and tell me what you would have done differently?

I am not aware of anything that I think can not be done with Weasyprint except the "trending sum on top and end of each page" which can not be solved the old solution either.

On the other hand, the ease of creating beautiful docs with this solution is amazing. I think I we will continue this way.

@andywuest @DanSman what do you think?

**Comment by DanSman** [comment]
Hi

> On the other hand, the ease of creating beautiful docs with this solution is amazing. I think I we will continue this way.

Yep, sounds good to me. 

Would it still be possible to disable to show the prices (only amount at the end)? 

Btw. The new option to disable the prices is not what I meant. The problem is, that I can't see the prices myself, when I create a quote or invoice. But maybe I can create an issue in addition to this new feature. But I have edited the .trml file to fit my needs. Would that work with weasyprint as well?

**Comment by liZe** [comment]
> @liZe would you mind to 'review' what I did and tell me what you would have done differently?

It looks nice :smile:.

Tweaking tables is an endless work, but here are some helpful features you can use in the future:
- you can force [tabular numbers](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric), even if your font doesn’t use them by default,
- you can use a [fixed table layout](https://developer.mozilla.org/fr/docs/Web/CSS/table-layout) if you want to allocate fixed widths for your columns,
- playing with font size, line height and hyphenation can help if your descriptions are usually long,
- you can try to put `break-*` rules around the tables and the paragraphs, and try different configurations to check that you always get what you want. There’s no perfect solution, but you can definitely avoid most of the worst cases you often meet when invoices are automatically generated with other tools.

One last little thing you probably didn’t notice: your invoice suffers from #751 (and I’m really sorry, because you can’t unsee what you’ve just seen :wink:.)

**Comment by dragotin** [comment]
Kraft Version 0.95 now supports WeasyPrint  to render PDF. @liZe thanks for that great project!

**Comment by liZe** [comment]
> Kraft Version 0.95 now supports WeasyPrint to render PDF. @liZe thanks for that great project!

Have fun! And don’t hesitate to report the issues you may find.
